### ISSUE TITLE
Controlled Vocabulary Terms

### ISSUE THREAD

**Issue by robragsdale** [ioos/vocabularies#9]
@emiliom @shane-axiom I found this url (http://fake.org/RA...) cited for a subset of vocabulary terms  in the services ([NANOOS](http://data.nanoos.org/52nsos/sos/kvp?service=SOS&request=GetCapabilities&acceptVersions=1.0.0), [CeNCOOS](http://sos.cencoos.org/sos/sos/kvp?service=SOS&request=GetCapabilities&acceptVersions=1.0.0), [AOOS](http://sos.aoos.org/sos/sos/kvp?service=SOS&request=GetCapabilities&acceptVersions=1.0.0)).  What is the origin for this URL, here is an example 'http://fake.org/nanoos/measurement_label/A1_PhotActiveRad'?  I get an error when I try to go the site.  Why did you decide to cite terms here instead of one of the CF or IOOS vocabularies?  Is it because you could not find a term in either of those two vocabularies to match what you needed?     

http://fake.org/nanoos/measurement_label/A1_PhotActiveRad
http://fake.org/nanoos/measurement_label/A1_Rain
http://fake.org/nanoos/measurement_label/A2_Rain
http://fake.org/nanoos/measurement_label/H1_ColoredDOM 
http://fake.org/nanoos/measurement_label/H1_Discharge
http://fake.org/nanoos/measurement_label/H1_FluorescMax
http://fake.org/nanoos/measurement_label/H1_FluorescMin
http://fake.org/nanoos/measurement_label/H1_PhrthrnFluoresc
http://fake.org/nanoos/measurement_label/H1_Pressure
http://fake.org/nanoos/measurement_label/H1_QuantumYld
http://fake.org/nanoos/measurement_label/H1_RedoxPot
http://fake.org/nanoos/measurement_label/H1_ScatterCoeff
http://fake.org/nanoos/measurement_label/H2_Nitrate
http://fake.org/nanoos/measurement_label/H2_Turbidity
http://fake.org/nanoos/measurement_label/H3_Turbidity

**Comment by emiliom** [comment]
I've updated these parameter vocabulary url's to use CF and IOOS terms on MMI, for most of them. I couldn't find equivalent terms for 4 of them, but they're infrequent and somewhat more exotic. FYI, these are variables we've been using for years, even before IOOS developed the current parameter vocabulary policy. With parameters such as these that were already available on an asset and are not present on either CF or IOOS parameter vocabularies, the pragmatic choice one faces initially is either blocking those variables from the data service (which is both extra work and counter productive), or using a temporary, non-resolving uri as a placeholder. The [process described in the Vocabularies README for "new" terms](https://github.com/ioos/vocabularies#vocabulary-selection-and-use) is not one with a clear time frame or sense of level of effort involved, yet.

FYI, the 4 parameters are (based on the ending name on the non-resolving uri's): H1_FluorescMin and H1_FluorescMax (Fluorescence minimum and maximum), H1_PhrthrnFluoresc (Phycoerythrin Fluorescence) and H1_RedoxPot (redox potential). I would need to get more complete definitions from the providers who measure these parameters, before we can take further steps.
